---
common:
  pidfile_directory: {{ robot_sweatshop_runtime_root }}
  logfile_directory: {{ robot_sweatshop_logfile_root }}
  user_config_directory: {{ robot_sweatshop_config_root }}

input:
  http:
    port: {{ robot_sweatshop_http_input_port }}
    bind: {{ robot_sweatshop_http_input_host }}

queue:
  moneta_directory: {{ robot_sweatshop_db_root }}

assembler:
  job_directory: {{ robot_sweatshop_config_root }}/jobs

worker:
  workspace_directory: {{ robot_sweatshop_config_root }}/workspaces
